using Godot;
using LostCrownlike.Core;

namespace LostCrownlike.UI;

/// <summary>
/// Player HUD: health bar, boss bar, transient checkpoint prompt.
///
/// The ability icons are gone with the crystals. Four slots that light up one
/// by one say "you are collecting things"; four slots lit from the first frame
/// say nothing at all, and cost screen.
/// Pure consumer of LostCrownlike.Core.EventBus — never references PlayerController
/// or any other subsystem's types (see ARCHITECTURE.md "### UI").
/// </summary>
public partial class Hud : Control
{
    [Export] public int MaxHealth = 100;

    private int _currentHealth;

    private ProgressBar _healthBar;
    private Label _healthLabel;
    private Label _checkpointPrompt;
    private Timer _checkpointTimer;
    private Label _runCompleteBanner;
    private ProgressBar _bossBar;
    private Label _bossLabel;
    private Label _roomLabel;
    private ColorRect _parryFlash;

    // -- The Crucible ------------------------------------------------------

    /// The four state colours, in HeatState order. Indexed by the int the
    /// signal carries, so a state added later fails loudly at the index rather
    /// than silently drawing the wrong colour.
    private static readonly Color[] HeatColors =
    {
        new(0.42f, 0.29f, 0.20f),   // Tempered  #6B4A32 dull iron
        new(0.88f, 0.54f, 0.17f),   // Kindled   #E08A2C amber
        new(1.00f, 0.35f, 0.15f),   // Molten    #FF5A26 orange-red
        new(1.00f, 0.82f, 0.29f),   // Flashover #FFD24A white-hot
    };

    /// Where the warning starts, as a fraction of the bar. Two and a half
    /// seconds of notice at the branch's worst gain rate, which is the whole
    /// point: an alarm that fires as the thing happens is a report, not a
    /// warning.
    private const float AlarmAt = 0.90f;

    private const float HeatColorTransitionSeconds = 0.25f;
    private const int StreakPips = 4;

    private ProgressBar _heatBar;
    private StyleBoxFlat _heatFill;
    private ColorRect _heatTick40;
    private ColorRect _heatTick70;
    private ColorRect[] _streakPips;
    private ColorRect _flashoverFlash;

    // -- Full-screen tension overlays ---------------------------------------
    //
    // Two radial gradients that live at the edges of the frame and stay out of
    // the middle of it. Both are built once, in _Ready, and animated by writing
    // a single Modulate alpha per frame -- no tween objects created per pulse,
    // no textures rebuilt, nothing allocated after startup.
    //
    // GradientTexture2D rather than a shader or an imported PNG: the gradient
    // is generated by the engine from four numbers, which keeps the project's
    // "no external asset files" rule intact and leaves the falloff tunable
    // without opening an image editor.

    /// #8A0B0B. Dark and desaturated on purpose -- a bright red vignette reads
    /// as a damage flash, and this is a STATE, not an event.
    private static readonly Color LowHealthColor = new(0.541f, 0.043f, 0.043f);

    /// #FF9515.
    private static readonly Color FlashoverEdgeColor = new(1f, 0.584f, 0.082f);

    /// 1.2Hz, matched to the low-health heartbeat in AudioManager. The eye and
    /// the ear reporting the same fact on the same beat is what makes it read
    /// as one warning rather than two problems.
    [Export] public float LowHealthPulseHz { get; set; } = 1.2f;
    [Export] public float LowHealthPeakAlpha { get; set; } = 0.35f;
    [Export] public float LowHealthFraction { get; set; } = 0.25f;

    /// 3Hz, matched to the heat bar's own alarm and to the audio sizzle.
    [Export] public float FlashoverPulseHz { get; set; } = 3f;
    [Export] public float FlashoverPeakAlpha { get; set; } = 0.40f;

    /// How fast an overlay fades once its condition stops holding. Not
    /// instant: a vignette that vanishes on the frame a heal lands reads as a
    /// glitch, and the whole point of these is that they are moods.
    [Export] public float OverlayFadeSpeed { get; set; } = 3.2f;

    private TextureRect _lowHealthVignette;
    private TextureRect _flashoverEdge;
    private float _lowHealthAlpha;
    private float _flashoverAlpha;
    private float _overlayTime;
    private Label _embersCounter;
    private RuneForgeModal _runeModal;

    private bool _inBranch;
    private float _heat01;
    private int _heatState;
    private float _alarmTime;

    private Color _heatColorFrom = HeatColors[0];
    private Color _heatColorTo = HeatColors[0];
    private float _heatColorT = 1f;

    public override void _Ready()
    {
        _healthBar = GetNode<ProgressBar>("%HealthBar");
        _healthLabel = GetNode<Label>("%HealthLabel");
        _checkpointPrompt = GetNode<Label>("%CheckpointPrompt");
        _checkpointTimer = GetNode<Timer>("%CheckpointTimer");

        _currentHealth = MaxHealth;
        _healthBar.MaxValue = MaxHealth;
        _healthBar.Value = _currentHealth;
        UpdateHealthLabel();
        _checkpointPrompt.Visible = false;

        _checkpointTimer.OneShot = true;
        _checkpointTimer.Timeout += OnCheckpointTimerTimeout;

        // Built here rather than in Hud.tscn. The HUD reaches its nodes by
        // unique name, so a scene-authored banner would be one more binding to
        // keep in sync with a hand-edited .tscn; the round-1 camera bug in this
        // project was exactly that class of failure. Nothing else needs to
        // address this node.
        _runCompleteBanner = new Label
        {
            Name = "RunCompleteBanner",
            Text = "RUN COMPLETE",
            Visible = false,
            HorizontalAlignment = HorizontalAlignment.Center,
            VerticalAlignment = VerticalAlignment.Center,
            MouseFilter = MouseFilterEnum.Ignore,
        };
        _runCompleteBanner.SetAnchorsPreset(LayoutPreset.FullRect);
        _runCompleteBanner.AddThemeFontSizeOverride("font_size", 48);
        // The banner lands wherever the player finished, which is a lit wall
        // as often as a dark one, so white-on-anything needs an outline to stay
        // legible rather than a colour chosen for one screenshot.
        _runCompleteBanner.AddThemeColorOverride("font_outline_color", new Color(0f, 0f, 0f, 0.85f));
        _runCompleteBanner.AddThemeConstantOverride("outline_size", 10);
        AddChild(_runCompleteBanner);

        BuildBossBar();
        BuildRoomLabel();
        BuildParryFlash();
        BuildHeatBar();
        BuildStreakPips();
        BuildFlashoverFlash();
        BuildTensionOverlays();
        BuildEmbersCounter();
        BuildRuneModal();

        if (EventBus.Instance != null)
        {
            EventBus.Instance.PlayerDamaged += OnPlayerDamaged;
            EventBus.Instance.PlayerHealthChanged += OnPlayerHealthChanged;
            EventBus.Instance.PlayerDied += OnPlayerDied;
            EventBus.Instance.CheckpointReached += OnCheckpointReached;
            EventBus.Instance.RunCompleted += OnRunCompleted;
            EventBus.Instance.BossStateChanged += OnBossStateChanged;
            EventBus.Instance.RoomEntered += OnRoomEntered;
            EventBus.Instance.Parried += OnParried;
            EventBus.Instance.BranchEntered += OnBranchEntered;
            EventBus.Instance.HeatChanged += OnHeatChanged;
            EventBus.Instance.ParryStreakChanged += OnParryStreakChanged;
            EventBus.Instance.Flashover += OnFlashover;
            EventBus.Instance.EmbersChanged += OnEmbersChanged;
            EventBus.Instance.RuneForgeRequested += OnRuneForgeRequested;
            EventBus.Instance.LevelTransitionRequested += (_, _) =>
            {
                if (_runCompleteBanner != null) _runCompleteBanner.Visible = false;
            };
        }
    }

    public override void _ExitTree()
    {
        if (EventBus.Instance != null)
        {
            EventBus.Instance.PlayerDamaged -= OnPlayerDamaged;
            EventBus.Instance.PlayerHealthChanged -= OnPlayerHealthChanged;
            EventBus.Instance.PlayerDied -= OnPlayerDied;
            EventBus.Instance.CheckpointReached -= OnCheckpointReached;
            EventBus.Instance.BossStateChanged -= OnBossStateChanged;
            EventBus.Instance.RoomEntered -= OnRoomEntered;
            EventBus.Instance.Parried -= OnParried;
            EventBus.Instance.BranchEntered -= OnBranchEntered;
            EventBus.Instance.HeatChanged -= OnHeatChanged;
            EventBus.Instance.ParryStreakChanged -= OnParryStreakChanged;
            EventBus.Instance.Flashover -= OnFlashover;
            EventBus.Instance.EmbersChanged -= OnEmbersChanged;
            EventBus.Instance.RuneForgeRequested -= OnRuneForgeRequested;
        }

        if (_checkpointTimer != null)
        {
            _checkpointTimer.Timeout -= OnCheckpointTimerTimeout;
        }
    }

    private void OnPlayerDamaged(int amount, Vector3 sourcePosition, Vector3 knockback, bool isCritical)
    {
        // Intentionally does not change the bar: health is rendered from
        // PlayerHealthChanged, the authoritative broadcast. Kept as the hook
        // for damage-only feedback (flash, shake) that must not fire on heals.
    }

    private void OnPlayerHealthChanged(int current, int max)
    {
        MaxHealth = max;
        _currentHealth = Mathf.Clamp(current, 0, max);
        _healthBar.MaxValue = max;
        _healthBar.Value = _currentHealth;
        UpdateHealthLabel();
    }

    private void OnPlayerDied()
    {
        // Deliberately does NOT write the bar. PlayerHealthChanged is the only
        // writer; this handler used to zero it and, because respawn happens
        // inside the PlayerDied emission (SaveManager subscribes first, as an
        // autoload, and its handler calls Respawn which broadcasts 100/100),
        // this ran LAST and stamped the bar back to 0 — leaving a fully healed
        // player showing 0/100 for the rest of the run.
    }

    
    private void OnCheckpointReached(string checkpointId)
    {
        _checkpointPrompt.Text = $"Checkpoint Reached: {checkpointId}";
        _checkpointPrompt.Visible = true;
        _checkpointTimer.Start();
    }

    private void OnRunCompleted(int roomsCleared)
    {
        if (_runCompleteBanner == null) return;
        // The banner has to say what to DO. Showing only "RUN COMPLETE" left the
        // player standing in a finished room with no visible way forward.
        _runCompleteBanner.Text = "RUN COMPLETE — " + roomsCleared + " rooms" + System.Environment.NewLine + "press JUMP for a new run";
        _runCompleteBanner.Visible = true;
    }

    private void OnCheckpointTimerTimeout()
    {
        _checkpointPrompt.Visible = false;
    }

    /// Built in code for the same reason as the banner: the HUD addresses its
    /// scene nodes by unique name, and one more hand-edited .tscn binding is
    /// one more thing that can silently stop resolving.
    private void BuildBossBar()
    {
        _bossLabel = new Label
        {
            Name = "BossLabel",
            Text = "THE WARDEN",
            Visible = false,
            HorizontalAlignment = HorizontalAlignment.Center,
            MouseFilter = MouseFilterEnum.Ignore,
        };
        _bossLabel.SetAnchorsPreset(LayoutPreset.CenterTop);
        _bossLabel.AnchorLeft = 0.25f;
        _bossLabel.AnchorRight = 0.75f;
        _bossLabel.OffsetTop = 18f;
        _bossLabel.OffsetBottom = 42f;
        _bossLabel.OffsetLeft = 0f;
        _bossLabel.OffsetRight = 0f;
        _bossLabel.AddThemeColorOverride("font_outline_color", new Color(0f, 0f, 0f, 0.85f));
        _bossLabel.AddThemeConstantOverride("outline_size", 6);
        AddChild(_bossLabel);

        _bossBar = new ProgressBar
        {
            Name = "BossBar",
            Visible = false,
            MinValue = 0,
            MaxValue = 100,
            Value = 100,
            ShowPercentage = false,
            MouseFilter = MouseFilterEnum.Ignore,
        };
        _bossBar.SetAnchorsPreset(LayoutPreset.CenterTop);
        _bossBar.AnchorLeft = 0.25f;
        _bossBar.AnchorRight = 0.75f;
        _bossBar.OffsetTop = 44f;
        _bossBar.OffsetBottom = 58f;
        _bossBar.OffsetLeft = 0f;
        _bossBar.OffsetRight = 0f;
        AddChild(_bossBar);
    }

    /// The armour is the fight's whole rule, so the bar says which state the
    /// boss is in rather than only how much is left: grey while armoured, lit
    /// while the parry window is open. Without that the player sees a bar that
    /// barely moves and concludes the game is broken, which is the correct
    /// conclusion from the information on screen.
    private void OnBossStateChanged(bool alive, float healthFraction, bool armoured, bool enraged)
    {
        if (_bossBar == null) return;

        _bossBar.Visible = alive;
        _bossLabel.Visible = alive;
        if (!alive) return;

        _bossBar.Value = healthFraction * 100f;
        _bossLabel.Text = enraged ? "THE WARDEN  —  ENRAGED" : "THE WARDEN";

        var fill = new StyleBoxFlat
        {
            BgColor = armoured
                ? new Color(0.42f, 0.40f, 0.38f)     // absorbing: the bar will barely move
                : new Color(0.95f, 0.78f, 0.30f),    // open: spend the window
        };
        _bossBar.AddThemeStyleboxOverride("fill", fill);
    }

    /// Where you are in the run. Worth the pixels only since the run became
    /// ten rooms of 200 metres: at two minutes you keep count yourself.
    private void BuildRoomLabel()
    {
        _roomLabel = new Label
        {
            Name = "RoomLabel",
            Text = "",
            HorizontalAlignment = HorizontalAlignment.Right,
            MouseFilter = MouseFilterEnum.Ignore,
        };
        _roomLabel.SetAnchorsPreset(LayoutPreset.TopRight);
        _roomLabel.AnchorLeft = 1f;
        _roomLabel.AnchorRight = 1f;
        _roomLabel.OffsetLeft = -170f;
        _roomLabel.OffsetRight = -18f;
        _roomLabel.OffsetTop = 16f;
        _roomLabel.OffsetBottom = 38f;
        _roomLabel.AddThemeColorOverride("font_color", new Color(0.86f, 0.80f, 0.68f));
        _roomLabel.AddThemeColorOverride("font_outline_color", new Color(0f, 0f, 0f, 0.85f));
        _roomLabel.AddThemeConstantOverride("outline_size", 6);
        AddChild(_roomLabel);
    }

    private void OnRoomEntered(int index, int total)
    {
        if (_roomLabel == null) return;
        // The last room is named rather than numbered: "10 of 10" and "the
        // Warden" are the same fact, and only one of them tells you to be
        // ready for it.
        _roomLabel.Text = index >= total - 1 ? "THE WARDEN" : $"Room {index + 1} of {total}";
    }

    private void BuildParryFlash()
    {
        _parryFlash = new ColorRect
        {
            Name = "ParryFlash",
            Color = new Color(1f, 0.9f, 0.45f, 0f),
            Visible = false,
            MouseFilter = MouseFilterEnum.Ignore,
        };
        _parryFlash.SetAnchorsPreset(LayoutPreset.FullRect);
        AddChild(_parryFlash);
    }

    private void OnParried(bool perfect, Vector3 atPosition)
    {
        if (!perfect || _parryFlash == null || !IsInsideTree()) return;
        _parryFlash.Visible = true;
        _parryFlash.Color = new Color(1f, 0.92f, 0.5f, 0.26f);
        var tween = CreateTween();
        if (tween == null) return;
        tween.TweenProperty(_parryFlash, "color:a", 0f, 0.16f)
             .SetTrans(Tween.TransitionType.Quad)
             .SetEase(Tween.EaseType.Out);
        tween.TweenCallback(Callable.From(() =>
        {
            if (_parryFlash != null && IsInstanceValid(_parryFlash))
                _parryFlash.Visible = false;
        }));
    }

    private void UpdateHealthLabel()
    {
        _healthLabel.Text = $"{_currentHealth} / {MaxHealth}";
    }

    // ======================================================================
    //  The Crucible: heat bar, streak pips, flashover
    // ======================================================================

    /// <summary>
    /// The heat bar and its two threshold marks.
    ///
    /// Built in code and parented to the HUD ROOT rather than to the health
    /// bar's parent, then positioned from the health bar's global rect every
    /// frame. The health bar comes from Hud.tscn and this file does not get to
    /// assume what contains it -- a Control inside a Container has its Position
    /// overwritten by the layout, and a bar that silently snaps to the corner
    /// is the kind of thing nobody notices until a screenshot.
    ///
    /// The ticks are children of the bar. A player has to know WHERE the rules
    /// change, not merely that they do: without the marks at 40 and 70 the
    /// colour shifts are something that happens TO you.
    /// </summary>
    private void BuildHeatBar()
    {
        _heatFill = new StyleBoxFlat { BgColor = HeatColors[0] };

        _heatBar = new ProgressBar
        {
            Name = "HeatBar",
            Visible = false,
            MinValue = 0,
            MaxValue = 100,
            Value = 0,
            ShowPercentage = false,
            MouseFilter = MouseFilterEnum.Ignore,
        };
        _heatBar.SetAnchorsPreset(LayoutPreset.TopLeft);
        _heatBar.AddThemeStyleboxOverride("fill", _heatFill);
        _heatBar.AddThemeStyleboxOverride("background", new StyleBoxFlat
        {
            BgColor = new Color(0.10f, 0.07f, 0.06f, 0.85f),
        });
        AddChild(_heatBar);

        _heatTick40 = BuildTick();
        _heatTick70 = BuildTick();
    }

    private ColorRect BuildTick()
    {
        var tick = new ColorRect
        {
            Name = "HeatTick",
            Color = new Color(0.06f, 0.05f, 0.04f, 0.9f),
            MouseFilter = MouseFilterEnum.Ignore,
        };
        _heatBar.AddChild(tick);
        return tick;
    }

    /// <summary>
    /// Four pips beside the health bar. They light one at a time as perfect
    /// parries chain and all go dark together on any damage, which is exactly
    /// what the streak does -- the row is the rule, drawn.
    /// </summary>
    private void BuildStreakPips()
    {
        _streakPips = new ColorRect[StreakPips];
        for (int i = 0; i < StreakPips; i++)
        {
            _streakPips[i] = new ColorRect
            {
                Name = $"StreakPip{i}",
                Color = PipColor(false),
                Visible = false,
                MouseFilter = MouseFilterEnum.Ignore,
            };
            _streakPips[i].SetAnchorsPreset(LayoutPreset.TopLeft);
            AddChild(_streakPips[i]);
        }
    }

    private static Color PipColor(bool lit) => lit
        ? new Color(1f, 0.86f, 0.38f, 0.95f)
        : new Color(0.30f, 0.24f, 0.20f, 0.55f);

    /// <summary>
    /// The two mood overlays, built once.
    ///
    /// They are added BEFORE the flashover flash in z-order terms only by
    /// virtue of being added after it in _Ready -- Godot draws siblings in
    /// child order, so the last one added is on top. The white-hot flash is a
    /// momentary event and must sit over the moods, so it is created first and
    /// these two go above... which is the wrong way round, and is why both of
    /// these explicitly move themselves BELOW it.
    /// </summary>
    private void BuildTensionOverlays()
    {
        _lowHealthVignette = BuildRadialOverlay("LowHealthVignette", LowHealthColor, edgeStop: 0.42f);
        _flashoverEdge = BuildRadialOverlay("FlashoverEdge", FlashoverEdgeColor, edgeStop: 0.62f);

        // Under the flash, over everything else. A vignette drawn on top of the
        // flashover's own white-out would tint the one frame that is supposed
        // to be pure light.
        if (_flashoverFlash != null)
        {
            MoveChild(_lowHealthVignette, _flashoverFlash.GetIndex());
            MoveChild(_flashoverEdge, _flashoverFlash.GetIndex());
        }
    }

    /// <summary>
    /// A full-screen radial gradient: clear in the middle, coloured at the
    /// edges. Generated by the engine from a handful of numbers rather than
    /// imported, which keeps the no-external-assets rule and leaves the falloff
    /// tunable without an image editor.
    /// </summary>
    /// <param name="edgeStop">Where the colour starts coming in, 0 at the
    /// centre and 1 at the corner. Higher is a tighter frame around the edge.</param>
    private TextureRect BuildRadialOverlay(string name, Color tint, float edgeStop)
    {
        var gradient = new Gradient
        {
            Offsets = new[] { 0f, edgeStop, 1f },
            Colors = new[]
            {
                new Color(tint.R, tint.G, tint.B, 0f),
                new Color(tint.R, tint.G, tint.B, 0f),
                new Color(tint.R, tint.G, tint.B, 1f),
            },
        };

        var texture = new GradientTexture2D
        {
            Gradient = gradient,
            Width = 256,
            Height = 256,
            Fill = GradientTexture2D.FillEnum.Radial,
            FillFrom = new Vector2(0.5f, 0.5f),
            FillTo = new Vector2(1.0f, 0.5f),
        };

        var rect = new TextureRect
        {
            Name = name,
            Texture = texture,
            // Stretched to whatever the window is. The gradient is 256x256 and
            // is meant to be smeared: it has no detail to lose.
            StretchMode = TextureRect.StretchModeEnum.Scale,
            MouseFilter = MouseFilterEnum.Ignore,
            Modulate = new Color(1f, 1f, 1f, 0f),
            Visible = false,
        };
        rect.SetAnchorsPreset(LayoutPreset.FullRect);
        AddChild(rect);
        return rect;
    }

    private void BuildFlashoverFlash()
    {
        _flashoverFlash = new ColorRect
        {
            Name = "FlashoverFlash",
            Color = new Color(1f, 0.94f, 0.72f, 0f),
            Visible = false,
            MouseFilter = MouseFilterEnum.Ignore,
        };
        _flashoverFlash.SetAnchorsPreset(LayoutPreset.FullRect);
        AddChild(_flashoverFlash);
    }

    /// <summary>
    /// The branch changed. An empty name means there is no branch any more,
    /// which is the only way this HUD can know the Crucible ended: room 4's
    /// door is an ordinary exit and says nothing about leaving.
    ///
    /// A heat broadcast is what actually reveals the bar. Every branching
    /// portal emits this signal -- the Catacombs and the Act II shortcut
    /// included -- and only one of them is ever followed by a HeatChanged. So
    /// the HUD never names the branch it is drawing, which is the point: it
    /// consumes the vocabulary and holds no opinion about the world.
    /// </summary>
    private void OnBranchEntered(string branchName)
    {
        _inBranch = !string.IsNullOrEmpty(branchName);

        if (_inBranch) return;

        _heat01 = 0f;
        _alarmTime = 0f;
        SetHeatVisible(false);
        SetStreak(0);
    }

    private void OnHeatChanged(float heat01, int state)
    {
        if (!_inBranch) return;

        _heat01 = Mathf.Clamp(heat01, 0f, 1f);

        if (state != _heatState)
        {
            _heatState = state;
            // Transition from wherever the colour actually IS, not from the
            // previous state's nominal colour: a state that changes twice
            // inside 0.25s would otherwise jump.
            _heatColorFrom = CurrentHeatColor();
            _heatColorTo = HeatColors[Mathf.Clamp(state, 0, HeatColors.Length - 1)];
            _heatColorT = 0f;
        }

        SetHeatVisible(true);
    }

    private void SetHeatVisible(bool visible)
    {
        if (_heatBar != null) _heatBar.Visible = visible;
        if (_streakPips == null) return;
        foreach (var pip in _streakPips) pip.Visible = visible;
    }

    private Color CurrentHeatColor() => _heatColorFrom.Lerp(_heatColorTo, Mathf.Clamp(_heatColorT, 0f, 1f));

    private void OnParryStreakChanged(int streak) => SetStreak(streak);

    private void SetStreak(int streak)
    {
        if (_streakPips == null) return;
        for (int i = 0; i < _streakPips.Length; i++)
            _streakPips[i].Color = PipColor(i < streak);
    }

    /// <summary>
    /// A full-screen white-hot flash. The camera shake is NOT here: shaking the
    /// view is the camera's business, and it listens to the same signal. A HUD
    /// that reached for the camera would be the one place in this project where
    /// the interface touches a gameplay node.
    /// </summary>
    private void OnFlashover(Vector3 atPosition)
    {
        if (_flashoverFlash == null || !IsInsideTree()) return;

        _flashoverFlash.Visible = true;
        _flashoverFlash.Color = new Color(1f, 0.94f, 0.72f, 0.55f);

        var tween = CreateTween();
        if (tween == null) return;
        tween.TweenProperty(_flashoverFlash, "color:a", 0f, 0.42f)
             .SetTrans(Tween.TransitionType.Quad)
             .SetEase(Tween.EaseType.Out);
        tween.TweenCallback(Callable.From(() =>
        {
            if (_flashoverFlash != null && IsInstanceValid(_flashoverFlash))
                _flashoverFlash.Visible = false;
        }));
    }

    /// <summary>
    /// Layout and animation for the heat row.
    ///
    /// Position is recomputed from the health bar's global rect every frame
    /// rather than once at _Ready. Control layout settles over the first
    /// frames and again on every window resize, and a bar placed once sits
    /// where the health bar USED to be.
    /// </summary>
    public override void _Process(double delta)
    {
        // The overlays run FIRST and unconditionally. They are not part of the
        // heat row and must keep working outside the Crucible -- the low-health
        // vignette is the one piece of feedback that matters most in a room
        // with no heat bar in it at all.
        TickTensionOverlays((float)delta);

        if (_heatBar == null || _healthBar == null) return;
        if (!_heatBar.Visible) return;

        float dt = (float)delta;

        LayoutHeatRow();

        if (_heatColorT < 1f)
            _heatColorT = Mathf.Min(1f, _heatColorT + dt / HeatColorTransitionSeconds);

        _heatBar.Value = _heat01 * 100f;
        _heatFill.BgColor = CurrentHeatColor();

        // The alarm. Three hertz, and only in the last tenth of the bar: a
        // pulse that ran the whole time would be wallpaper by the second room.
        if (_heat01 >= AlarmAt)
        {
            _alarmTime += dt;
            float pulse = 0.55f + 0.45f * Mathf.Sin(_alarmTime * Mathf.Tau * 3f);
            _heatBar.Modulate = new Color(1f, 1f, 1f, 0.55f + 0.45f * pulse);
        }
        else
        {
            _alarmTime = 0f;
            _heatBar.Modulate = Colors.White;
        }
    }

    /// <summary>
    /// Both overlays, driven by a shared clock.
    ///
    /// One sine per overlay and two alpha writes: no tween is created, no
    /// texture is rebuilt, and nothing is allocated. The two pulse rates are
    /// deliberately different multiples of the same time base -- 1.2Hz and 3Hz
    /// -- so a player who is both nearly dead and about to be caught in a
    /// flashover sees two rhythms rather than one blur.
    ///
    /// Each target alpha is approached rather than assigned. A vignette that
    /// snapped on the frame health crossed 25% would read as a rendering
    /// glitch; these are moods, and a mood arrives.
    /// </summary>
    private void TickTensionOverlays(float dt)
    {
        if (_lowHealthVignette == null || _flashoverEdge == null) return;

        _overlayTime += dt;

        // -- low health ----------------------------------------------------
        bool lowHealth = _currentHealth > 0
                      && MaxHealth > 0
                      && _currentHealth <= MaxHealth * LowHealthFraction;

        float lowTarget = 0f;
        if (lowHealth)
        {
            // 0..1 rather than -1..1: the vignette breathes in and out of
            // clear, never darker-than-off.
            float pulse = 0.5f + 0.5f * Mathf.Sin(_overlayTime * Mathf.Tau * LowHealthPulseHz);
            lowTarget = pulse * LowHealthPeakAlpha;
        }

        _lowHealthAlpha = Mathf.MoveToward(_lowHealthAlpha, lowTarget, OverlayFadeSpeed * dt);
        ApplyOverlayAlpha(_lowHealthVignette, _lowHealthAlpha);

        // -- flashover -----------------------------------------------------
        // State 3 is HeatState.Flashover. Compared as the int the signal
        // carries, because the HUD holds no compile-time dependency on World
        // and the whole reason HeatChanged flattens the enum is so it does not
        // need one.
        bool flashover = _heatBar != null && _heatBar.Visible && _heatState == 3;

        float edgeTarget = 0f;
        if (flashover)
        {
            float pulse = 0.5f + 0.5f * Mathf.Sin(_overlayTime * Mathf.Tau * FlashoverPulseHz);
            edgeTarget = (0.45f + 0.55f * pulse) * FlashoverPeakAlpha;
        }

        _flashoverAlpha = Mathf.MoveToward(_flashoverAlpha, edgeTarget, OverlayFadeSpeed * dt);
        ApplyOverlayAlpha(_flashoverEdge, _flashoverAlpha);
    }

    /// Hidden at zero rather than merely transparent. A fully transparent
    /// full-screen TextureRect is still a quad the renderer blends every frame,
    /// and there are two of them.
    private static void ApplyOverlayAlpha(TextureRect rect, float alpha)
    {
        bool on = alpha > 0.002f;
        rect.Visible = on;
        if (!on) return;

        var m = rect.Modulate;
        m.A = alpha;
        rect.Modulate = m;
    }

    private void LayoutHeatRow()
    {
        var origin = GetGlobalRect().Position;
        var health = _healthBar.GetGlobalRect();

        const float barHeight = 10f;
        const float gap = 4f;
        const float pipSize = 9f;
        const float pipGap = 4f;

        float width = health.Size.X * 0.6f;
        var pos = health.Position - origin + new Vector2(0f, health.Size.Y + gap);

        _heatBar.Position = pos;
        _heatBar.Size = new Vector2(width, barHeight);

        // Marks at 40 and 70, in the bar's own space, two pixels wide.
        _heatTick40.Position = new Vector2(width * 0.40f, 0f);
        _heatTick40.Size = new Vector2(2f, barHeight);
        _heatTick70.Position = new Vector2(width * 0.70f, 0f);
        _heatTick70.Size = new Vector2(2f, barHeight);

        // Pips beside the HEALTH bar, not the heat bar: the streak is about
        // staying alive, and it belongs next to the number it protects.
        var pipOrigin = health.Position - origin + new Vector2(health.Size.X + 10f, (health.Size.Y - pipSize) * 0.5f);
        for (int i = 0; i < _streakPips.Length; i++)
        {
            _streakPips[i].Position = pipOrigin + new Vector2(i * (pipSize + pipGap), 0f);
            _streakPips[i].Size = new Vector2(pipSize, pipSize);
        }
    }

    private void BuildEmbersCounter()
    {
        _embersCounter = new Label
        {
            Name = "EmbersCounter",
            Text = "0 🔥",
            HorizontalAlignment = HorizontalAlignment.Right,
            MouseFilter = MouseFilterEnum.Ignore,
        };
        _embersCounter.SetAnchorsPreset(LayoutPreset.TopRight);
        _embersCounter.AnchorLeft = 1f;
        _embersCounter.AnchorRight = 1f;
        _embersCounter.OffsetLeft = -180f;
        _embersCounter.OffsetTop = 18f;
        _embersCounter.OffsetRight = -24f;
        _embersCounter.OffsetBottom = 44f;
        _embersCounter.AddThemeColorOverride("font_color", new Color(1.0f, 0.75f, 0.25f));
        _embersCounter.AddThemeColorOverride("font_outline_color", new Color(0f, 0f, 0f, 0.85f));
        _embersCounter.AddThemeConstantOverride("outline_size", 5);
        _embersCounter.AddThemeFontSizeOverride("font_size", 16);
        AddChild(_embersCounter);

        UpdateEmbersDisplay(Save.SaveManager.Instance?.Current?.TotalEmbers ?? 0);
    }

    private void BuildRuneModal()
    {
        _runeModal = new RuneForgeModal { Name = "RuneForgeModal" };
        AddChild(_runeModal);
    }

    private void OnEmbersChanged(int total) => UpdateEmbersDisplay(total);

    private void UpdateEmbersDisplay(int total)
    {
        if (_embersCounter != null && IsInstanceValid(_embersCounter))
            _embersCounter.Text = $"{total} 🔥";
        _runeModal?.RefreshUI();
    }

    private void OnRuneForgeRequested(bool open)
    {
        if (open) _runeModal?.Open();
        else _runeModal?.Close();
    }
}
